## earthkit-data: BUFR

In [1]:
import earthkit.data as ekd

## Getting the data

In [2]:
d = ekd.from_source("file", "synop_10.bufr")
d

### Featurelists and BUFR messages

A featuresist is similar to a fieldList, but it is an iterable of "features", where a "feature" can be anything. The best representation of BUFR data is a featurelist where the features are BUFR messages.

In [3]:
fl = d.to_featurelist()

In [4]:
len(fl)

10

In [5]:
fl.ls()

,edition,type,subtype,c,mv,lv,subsets,compr,typicalDate,typicalTime,ident,lat,lon
0,3,0,1,98,13,1,1,0,20230602,120000,91648,-10.75,179.50
1,3,0,1,98,13,1,1,0,20230602,120000,89514,-70.77,11.75
2,3,0,1,98,13,1,1,0,20230602,120000,60545,33.77,2.93
3,3,0,1,98,13,1,1,0,20230602,120000,30823,51.83,107.60
4,3,0,1,98,13,1,1,0,20230602,120000,30846,51.35,112.47
5,3,0,1,98,13,1,1,0,20230602,120000,48352,17.86,102.75
6,3,0,1,98,13,1,1,0,20230602,120000,98747,8.41,124.61
7,3,0,1,98,13,1,1,0,20230602,120000,68267,-26.50,29.98
8,3,0,1,98,13,1,1,0,20230602,120000,68592,-29.60,31.12
9,3,0,1,98,13,1,1,0,20230602,120000,91701,-2.77,-171.72

#### BUFR messages

In [6]:
# f is the first message in the featurelist
f = fl[0]
f

BUFRMessage(type=0,subType=1,subsets=1,20230602,120000)

In [7]:
f.describe()

### Subsetting

In [8]:
fl1 = fl.sel(dataSubCategory=1, ident=[60545, 48352])
fl1.ls()

,edition,type,subtype,c,mv,lv,subsets,compr,typicalDate,typicalTime,ident,lat,lon
0,3,0,1,98,13,1,1,0,20230602,120000,60545,33.77,2.93
1,3,0,1,98,13,1,1,0,20230602,120000,48352,17.86,102.75

### Converting to pandas

In [9]:
df = fl.to_pandas(columns=["latitude", "longitude",
                           "heightOfStation","airTemperatureAt2M"])
df

   latitude  longitude  heightOfStation  airTemperatureAt2M
0    -10.75     179.50              3.0               300.4
1    -70.77      11.75              NaN               255.2
2     33.77       2.93            763.0               296.3
3     51.83     107.60            515.0               291.6
4     51.35     112.47            743.0               287.4
5     17.86     102.75            176.0               307.9
6      8.41     124.61            188.0               299.4
7    -26.50      29.98           1774.0               281.9
8    -29.60      31.12            105.0               299.8
9     -2.77    -171.72              2.0               302.1

In [10]:
df = fl.to_pandas(reader="synop")
df

,stnid,lat,lon,elevation,time,t2m,rh2m,td2m,wind10m_speed,wind10m_dir,...,present_weather,precipitation_6h,precipitation_12h,min_t2m,max_t2m,mslp,pressure,cloud_cover,snow_depth,visibility
0,91648,-10.75,179.50,3.0,2023-06-02 12:00:00,300.4,None,298.1,4.0,80,...,2,0.0,NaN,None,None,101220.0,NaN,60,None,55000.0
1,89514,-70.77,11.75,NaN,2023-06-02 12:00:00,255.2,None,NaN,12.0,180,...,2,NaN,0.0,None,None,98780.0,NaN,40,None,10000.0
2,60545,33.77,2.93,763.0,2023-06-02 12:00:00,296.3,None,285.0,5.0,60,...,2,NaN,0.0,None,None,NaN,92720.0,90,None,8000.0
3,30823,51.83,107.60,515.0,2023-06-02 12:00:00,291.6,None,277.2,4.0,310,...,1,NaN,0.0,None,None,101640.0,95740.0,40,None,55000.0
4,30846,51.35,112.47,743.0,2023-06-02 12:00:00,287.4,None,277.7,4.0,230,...,1,NaN,0.6,None,None,101460.0,92970.0,75,None,55000.0
5,48352,17.86,102.75,176.0,2023-06-02 12:00:00,307.9,None,298.5,2.0,140,...,2,NaN,0.0,None,None,100190.0,98260.0,25,None,12000.0
6,98747,8.41,124.61,188.0,2023-06-02 12:00:00,299.4,None,296.7,1.0,150,...,5,0.0,NaN,None,None,100980.0,100120.0,10,None,15000.0
7,68267,-26.50,29.98,1774.0,2023-06-02 12:00:00,281.9,None,274.3,5.0,310,...,2,0.0,NaN,None,None,NaN,82650.0,0,None,20000.0
8,68592,-29.60,31.12,105.0,2023-06-02 12:00:00,299.8,None,293.3,6.0,40,...,2,0.0,NaN,None,None,101260.0,100220.0,0,None,20000.0
9,91701,-2.77,-171.72,2.0,2023-06-02 12:00:00,302.1,None,NaN,3.0,70,...,2,0.0,NaN,None,None,101190.0,NaN,40,None,55000.0